name: RSpec

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      radicale:
        image: xlrl/radicale
        ports:
        - 8000:8000
        env:
          RADICALE_USER: test
          RADICALE_PASS: test

    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.7.5
          - 3.0.3
          - 3.1.0

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: RSpec
      env:
        APPLE_USERNAME: ${{ secrets.APPLE_USERNAME }}
        APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        GOOGLE_USERNAME: calendavtest@gmail.com
        GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
        RADICALE_USERNAME: test
        RADICALE_PASSWORD: test
        RADICALE_HOST: http://127.0.0.1:8000
      run: bundle exec rspec
